### ISSUE TITLE
Subgraph not reflecting decreases in `For Sale Price`

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/geo-web-subgraph#19]
**Description**
The subgraph is not reflecting decreases in `For Sale Price` on the Cadastre made via the Edit function. Increases are showing. 

**Examples**
Parcel 0x2 (Statue of Liberty) should be .02. Parcel 0x5 (1 World Trade) should be .05.

**Comment by codynhat** [comment]
@gravenp This should be fixed now. Can you verify in the Cadastre?

**Comment by gravenp** [comment]
@codynhat Yup, changes are being reflected properly now. Good to go.

**Comment by gravenp** [comment]
Issue fixed with changes to the Subgraph. Closing ticket.
